### ISSUE TITLE
Settle on default pathline and CPO integrator options

### ISSUE THREAD

**Issue by adigitoleo** [Patol75/PyDRex#89]
It is tricky to find good default options for the scipy integrators in `Mineral.update_orientations` and `pathlines.get_pathline`. We need to settle on some defaults that should "work" (at least not crash) in common situations, and probably provide an interface to quickly/easily change those options.

Current status (checkboxes for when resolved):
- [x] ~~RNG seed of 13 causes GBS test with X=0.2 to hang at step 5/250~~ (nope, my mistake)
- [x] ~~RNG seed of 8845 causes hang at 347th matrix? (check if that persisted)~~ Can't reproduce with current atol/rtol/first_step settings, maybe solved
- [x] Can't handle certain numbers of grains ~~(or is it just memory?)~~ Too many ODE's for SciPy, solved by be0b15b

Pathline integrator:
- `RK45`, `atol=1e-99`, `rtol=1e-6`?

CPO integrator:
- `LSODA`, `atol=1e-99`, `rtol=1e-6`?

**Comment by adigitoleo** [comment]
The LSODA integrator hangs (takes minutes to resolve) when fed particular orientation matrices. It seems it happens when they are close to the identity matrix. In particular the following matrix has been found to cause issues:

```
 [[9.999999958227486e-01, 9.140296852091229e-05, 0.e+00],
  [-9.140296852091229e-05, 9.999999958227486e-01, -0.e+00],
  [-0.e+00, 0.e+00, 1.e+00]]]
```

**Comment by adigitoleo** [comment]
That matrix is the 347th matrix generated by the current stats.py RNG seed of 8845.

**Comment by adigitoleo** [comment]
Another thing to chase up: LSODA sometimes has trouble converging when the timesteps are large, e.g. > 1e11.

**Comment by adigitoleo** [comment]
LSODA also crashes with unexpected istate for crystals with > `4632` grains, doesn't seem to depend on the RNG seed used for the initial orientation condition nor the timestep resolution. Didn't have any luck getting it unstuck by trying different atol/rtol values either, crash persists without giving any explicit rtol/atol.

```
 lsoda--  rwork length needed, lenrw (=i1), exceeds lrw (=i2)
      in above message,  i1 =    741444   i2 =**********
```

**Comment by Patol75** [comment]
It is probably related to exceeding available memory.

**Comment by adigitoleo** [comment]
> It is probably related to exceeding available memory.

Not sure about that, 5000 grains is also failing on gadi with 500GB.
